<?php
/** BAJI premium footer */
if ( ! defined( 'ABSPATH' ) ) exit;
?>
</main><!-- #main-content -->
<footer id="colophon" class="baji-footer-v2" dir="rtl">
 <div class="bf-wrap">
  <div class="bf-top">
   <section class="bf-brand">
    <a class="bf-logo" href="<?php echo esc_url(home_url('/')); ?>">BAJI</a><div class="bf-tag">Be your best</div>
    <h3>باجی کیفیتی که با اولین پوشیدن حسش می‌کنی 🤍</h3>
    <p>باجی، همراه شما در انتخاب لباس‌هایی که ترکیبی از کیفیت، راحتی و استایل روز هستند. ما به لباس فقط به عنوان پوشش نگاه نمی‌کنیم؛ بلکه به عنوان بخشی از سبک زندگی شما.</p>
    <div class="bf-social"><?php foreach(array('instagram'=>'instagram','telegram'=>'telegram','whatsapp'=>'whatsapp','pinterest'=>'pinterest-p') as $k=>$i){$u=get_theme_mod('bajistyle_social_'.$k);if($u) echo '<a href="'.esc_url($u).'" target="_blank" rel="noopener"><i class="fa-brands fa-'.$i.'"></i></a>';} ?></div>
   </section>
   <nav class="bf-col"><h3>لینک‌های سریع</h3><a href="<?php echo esc_url(home_url('/')); ?>">صفحه اصلی</a><a href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>">فروشگاه</a><a href="<?php echo esc_url(home_url('/shop/?orderby=date')); ?>">جدیدترین محصولات</a><a href="<?php echo esc_url(home_url('/blog/')); ?>">مقالات و مجله باجی</a><a href="<?php echo esc_url(home_url('/about/')); ?>">درباره ما</a><a href="<?php echo esc_url(home_url('/contact/')); ?>">تماس با ما</a></nav>
   <nav class="bf-col"><h3>خدمات مشتریان</h3><a href="<?php echo esc_url(home_url('/faq/')); ?>">پاسخ به پرسش‌های متداول</a><a href="<?php echo esc_url(home_url('/terms/')); ?>">شرایط خرید و ارسال</a><a href="<?php echo esc_url(home_url('/terms/')); ?>">رویه بازگشت کالا</a><a href="<?php echo esc_url(home_url('/size-guide/')); ?>">راهنمای سایز</a><a href="<?php echo esc_url(get_privacy_policy_url() ?: home_url('/privacy-policy/')); ?>">حریم خصوصی</a><a href="<?php echo esc_url(home_url('/terms/')); ?>">قوانین و مقررات</a></nav>
   <section class="bf-news"><h3>عضویت در خبرنامه</h3><p>با عضویت در خبرنامه، از تخفیف‌ها و جدیدترین محصولات باخبر شوید.</p><form id="baji-newsletter-form" class="baji-newsletter-form" novalidate><?php wp_nonce_field('bajistyle_general_nonce','baji_newsletter_nonce'); ?><input id="baji-newsletter-email" name="newsletter_email" type="email" required placeholder="ایمیل شما"><button type="submit">عضویت</button></form><p class="baji-newsletter-message" role="status"></p><small>با ثبت ایمیل، قوانین حریم خصوصی را می‌پذیرم.</small></section>
  </div>
  <div class="bf-features"><div><i class="far fa-headset"></i><b>پشتیبانی پاسخگو</b><span>همیشه کنار شما هستیم</span></div><div><i class="far fa-shield-check"></i><b>پرداخت امن</b><span>با درگاه‌های معتبر</span></div><div><i class="far fa-truck"></i><b>ارسال سریع</b><span>به سراسر ایران</span></div><div><i class="far fa-gift"></i><b>خرید مطمئن</b><span>ضمانت کیفیت کالا</span></div></div>
  <div class="bf-trust">
   <div class="bf-badge"><strong>دیجی‌پی</strong><span>پرداخت مطمئن</span></div><div class="bf-badge"><strong>توروپی</strong><span>خرید اقساطی</span></div>
   <a class="bf-badge bf-img" target="_blank" rel="noopener" href="https://trustseal.enamad.ir/?id=661133&Code=KEQE0AsA3PbAohWIzUEBUZEejYgAGSdn"><img src="https://trustseal.enamad.ir/logo.aspx?id=661133&Code=KEQE0AsA3PbAohWIzUEBUZEejYgAGSdn" alt="نماد اعتماد الکترونیکی"><span>نماد اعتماد الکترونیکی</span></a>
   <div class="bf-badge"><strong>ساماندهی</strong><span>رسانه‌های دیجیتال</span></div><div class="bf-badge"><strong>کد اقتصادی</strong><span>اطلاعات کسب‌وکار</span></div>
  </div>
  <div class="bf-bottom"><span>BAJI — Be your best</span><span>تمامی حقوق این وب‌سایت متعلق به برند باجی است © <?php echo esc_html(gmdate('Y')); ?></span></div>
 </div>
</footer>
<style id="baji-footer-v2-css">
.baji-footer-v2{background:#0d0f0e;color:#f6f3ed;font-family:inherit}.bf-wrap{max-width:1380px;margin:auto;padding:72px 5vw 30px}.bf-top{display:grid;grid-template-columns:1.45fr .85fr .95fr 1.05fr;gap:0}.bf-top>section,.bf-top>nav{padding:0 32px;border-left:1px solid rgba(255,255,255,.1)}.bf-top>*:last-child{border-left:0}.bf-brand{padding-right:0!important}.bf-logo{display:block;color:#fff!important;font-family:Georgia,serif;font-size:58px;letter-spacing:.08em;line-height:1;text-decoration:none}.bf-tag{font-family:Georgia,serif;color:#d9c9b7;font-size:15px;margin:8px 0 28px;direction:ltr;text-align:right}.bf-brand h3,.bf-col h3,.bf-news h3{font-size:16px;color:#fff;margin:0 0 22px;font-weight:700}.bf-brand p,.bf-news p{color:#b8b8b4;line-height:2.1;font-size:13px;margin:0}.bf-brand h3{font-size:14px;margin-bottom:14px}.bf-social{display:flex;gap:12px;margin-top:26px;direction:ltr;justify-content:flex-end}.bf-social a{width:42px;height:42px;border:1px solid #555;border-radius:50%;display:grid;place-items:center;color:#fff!important;text-decoration:none}.bf-col{display:flex;flex-direction:column;gap:14px}.bf-col a{color:#c8c8c3!important;text-decoration:none;font-size:13px;transition:.2s}.bf-col a:hover{color:#e8d4bd!important}.bf-news input{width:100%;height:52px;background:transparent;border:1px solid #555;border-radius:12px;padding:0 15px;color:#fff;margin:22px 0 10px}.bf-news button{width:100%;height:52px;border:0;border-radius:10px;background:#ead9c5;color:#171717;font-weight:700;cursor:pointer}.bf-news small{display:block;color:#aaa;font-size:10px;margin-top:18px}.bf-features{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid #444;border-bottom:1px solid #444;margin-top:48px;padding:34px 0}.bf-features div{display:flex;flex-direction:column;align-items:center;gap:8px}.bf-features i{font-size:32px;color:#e7d3bd;margin-bottom:5px}.bf-features b{font-size:16px}.bf-features span{font-size:12px;color:#aaa}.bf-trust{display:grid;grid-template-columns:repeat(5,1fr);gap:24px;padding:42px 0;border-bottom:1px solid #444}.bf-badge{min-height:110px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;text-align:center;color:#fff!important;text-decoration:none}.bf-badge strong{font-size:20px}.bf-badge span{font-size:12px;color:#aaa}.bf-img img{width:64px;height:64px;object-fit:contain;background:#fff;border-radius:8px;padding:4px}.bf-bottom{display:flex;justify-content:space-between;align-items:center;padding-top:25px;font-size:11px;color:#aaa;direction:ltr}.bf-bottom span:first-child{font-family:Georgia,serif;color:#e9dfd4;font-size:14px}.bf-bottom span:last-child{direction:rtl}.baji-newsletter-message{font-size:11px!important;margin-top:8px!important}
@media(max-width:900px){.bf-wrap{padding:52px 24px 95px}.bf-top{grid-template-columns:1fr 1fr;gap:36px 0}.bf-top>section,.bf-top>nav{border-left:0;padding:0 20px}.bf-brand{grid-column:1/-1;padding:0!important}.bf-features{grid-template-columns:1fr 1fr;gap:30px}.bf-trust{grid-template-columns:repeat(3,1fr)}.bf-bottom{gap:20px;align-items:flex-start;flex-direction:column}}
@media(max-width:560px){.bf-wrap{padding-left:20px;padding-right:20px}.bf-top{grid-template-columns:1fr}.bf-brand{grid-column:auto}.bf-top>section,.bf-top>nav{padding:0;border-bottom:1px solid rgba(255,255,255,.08);padding-bottom:28px}.bf-logo{font-size:50px}.bf-social{justify-content:flex-start}.bf-features{grid-template-columns:1fr 1fr}.bf-features b{font-size:13px}.bf-trust{grid-template-columns:1fr 1fr;gap:16px}.bf-bottom{padding-bottom:10px}}
</style>
<div class="baji-mobile-bottom-nav md:hidden fixed bottom-0 inset-x-0 z-50 border-t border-gray-100 shadow-[0_-5px_15px_rgba(0,0,0,0.05)] flex items-center justify-around h-16 px-2" style="background-color:#fff!important;"><a href="<?php echo esc_url(home_url('/')); ?>" class="flex flex-col items-center justify-center gap-1 text-gray-500 flex-1"><i class="far fa-home text-xl"></i><span class="text-[10px]">خانه</span></a><button type="button" class="baji-cart-toggle flex flex-col items-center justify-center gap-1 text-gray-500 flex-1" aria-controls="baji-cart-panel"><i class="far fa-shopping-bag text-xl"></i><span class="text-[10px]">سبد خرید</span></button><a href="<?php echo esc_url(get_permalink(get_option('woocommerce_myaccount_page_id'))); ?>" class="flex flex-col items-center justify-center gap-1 text-gray-500 flex-1"><i class="far fa-user text-xl"></i><span class="text-[10px]">حساب من</span></a></div>
</div><!-- #page -->
<div id="baji-cart-panel" class="fixed inset-y-0 left-0 bg-white shadow-2xl transition-transform duration-300" style="z-index:9999;width:400px;max-width:100%;transform:translateX(-100%);"><div class="flex justify-between items-center p-4 border-b"><h3 class="font-bold">سبد خرید</h3><button id="baji-cart-close" class="text-2xl p-2">&times;</button></div><div class="p-4 overflow-y-auto widget_shopping_cart_content" style="height:calc(100vh - 65px);"><?php woocommerce_mini_cart(); ?></div></div><div id="baji-cart-overlay" class="fixed inset-0 backdrop-blur-sm" style="z-index:9998;background:rgba(0,0,0,.5);opacity:0;pointer-events:none"></div>
<?php wp_footer(); ?>
</body></html>